[project]
name = "tarot-bot"
version = "0.1.1"
description = "A silly bot for a Discord server that gives you tarot cards"
readme = "README.md"
requires-python = ">=3.13.5"
dependencies = [
    "discord>=2.3.2",
    "google-genai>=1.20.0",
    "python-dotenv>=1.1.0",
]
